### ISSUE TITLE
a100 vs a40

### ISSUE THREAD

**Issue by yosun** [lucataco/cog-sdxl-controlnet#2]
hey, your model has been stuck in starting quite a bit the last few days... just curious why you are running on replicate a40 instead of a100?

https://replicate.com/lucataco/sdxl-controlnet

**Comment by lucataco** [comment]
Most likely cold boots. If a model sees high demand, Replicate scales up multiple GPUs to meet the demand and you end up hitting some of the cold boot times. But that’s just a guess.

I initially chose the A40 because it was a new option on Replicate, and I was trying to optimize for speeds and cost at the time. If I change it now users will complain, however you are free to push this code to your own private instance running on an a100
